### ISSUE TITLE
Bot issuing duplicate comments

### ISSUE THREAD

**Issue by Timer** [chdsbd/kodiak#84] opened 2019-07-25 01:51 UTC
![image](https://user-images.githubusercontent.com/616428/61839861-2d7eff80-ae5d-11e9-9f78-10c55e6052bf.png)

https://github.com/zeit/next.js/pull/8061

I had to disable the bot as it was doing this on all open PRs. 
Also, if `require_automerge_label = true`, it shouldn't specify a label in its message.

Additionally, we've customized the label `automerge_label = "lgtm"` so this message seems hard-coded.

**Comment by chdsbd** [comment] 2019-07-25 01:57
Sorry about that. I'll try to reproduce this and get back to you.

**Comment by Timer** [comment] 2019-07-25 01:58
Here's our [`.kodiak.toml`](https://github.com/zeit/next.js/blob/canary/.kodiak.toml) if it's helpful.

**Comment by chdsbd** [comment] 2019-07-25 01:59
Do you mind sending me your branch protection settings for the target branch of the PR?

**Comment by Timer** [comment] 2019-07-25 02:08
![image](https://user-images.githubusercontent.com/616428/61840565-8ea7d280-ae5f-11e9-97f2-213f22f39675.png)

**Comment by chdsbd** [comment] 2019-07-25 02:09
Was the PR approved by a code owner when kodiak was trying to merge it?

**Comment by Timer** [comment] 2019-07-25 02:10
Yes

**Comment by Timer** [comment] 2019-07-25 02:10
This issue is different, OP was not approved by anyone.

**Comment by chdsbd** [comment] 2019-07-25 02:11
Ohhhhhhh. Okay. I know a piece of this problem.

**Comment by chdsbd** [comment] 2019-07-25 02:12
We prevent sending duplicate comments by removing the automerge label after adding the comment. Since we aren't using the automerge labels, we get a bunch of duplicate comments.

**Comment by Timer** [comment] 2019-07-25 02:12
Just to clarify #83 and this issue (#84) were on **different** PRs.

**Comment by chdsbd** [comment] 2019-07-25 02:13
Yeah, I think #83 must be something else.

**Comment by Timer** [comment] 2019-07-25 02:14
Hmm, random thought. `notify_on_conflict` and `require_automerge_label` don't really work well together.

`require_automerge_label = true` needs to imply `notify_on_conflict = false`, or at least only check for conflict once already approved.

**Comment by chdsbd** [comment] 2019-07-25 02:15
Yeah, I agree.

**Comment by Timer** [comment] 2019-07-25 02:15
I've disabled `notify_on_conflict` for now! 😄

**Comment by chdsbd** [comment] 2019-07-25 02:44
This should be fixed when #86 is deployed.

**Comment by sbdchd** [comment] 2019-07-25 02:45
The bad templating should be fixed in #88

**Comment by chdsbd** [comment] 2019-07-25 03:24
This change has been deployed.

**Comment by chdsbd** [comment] 2019-07-25 03:25
Please reopen if this doesn't fix it. 🤞

**Closed by chdsbd** 2019-07-25 03:24 UTC
Labels: bug
